/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package read_before_interview;

/**
 *
 * @author venka
 */
public class Top100GoogleQuestions {
    
}
/*

"Guess the Word"
"Maximum Points You Can Obtain from Cards"
"Logger Rate Limiter"
"Minimum Window Subsequence"
"String Transforms Into Another String"
"Max Value of Equation"ōtwo
"The Most Similar Path in a Graph"
"Range Module"
"Encode String with Shortest Length"
"Maximum Number of Visible Points"
"Optimal Account Balancing"
"Max Area of Island"
"Expressive Words"
"Random Pick with Weight"
"Employee Importance"
"Validate Stack Sequences"
"Robot Room Cleaner"
"Alphabet Board Path"
"Confusing Number II"
"Range Sum Query 2D - Mutable"
"Snapshot Array"
"Student Attendance Record II"
"Minimum Number of K Consecutive Bit Flips"
"Frog Position After T Seconds"
"Find Two Non-overlapping Sub-arrays Each With Target Sum"
"Count Square Submatrices with All Ones"
"Car Fleet"
"Find And Replace in String"
"Hand of Straights"
"Tiling a Rectangle with the Fewest Squares"
"Stone Game III"
"Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit"
"Delete Nodes And Return Forest"
"Longest Line of Consecutive One in Matrix"
"Sentence Screen Fitting"
"Sequence Reconstruction"
"Cracking the Safe"
"Sum of Distances in Tree"
"RLE Iterator"
"Longest Increasing Path in a Matrix"
"Swap Adjacent in LR String"
"Count of Smaller Numbers After Self"
"Number of Closed Islands"
"Maximal Rectangle"
"My Calendar I"
"Design Phone Directory"
"LFU Cache"
"Find Duplicate Subtrees"
"Russian Doll Envelopes"
"Kth Ancestor of a Tree Node"
"Number of Matching Subsequences"
"Strobogrammatic Number III"
"Two Sum"
"Binary Tree Cameras"
"Time Needed to Inform All Employees"
"Online Election"
"Strong Password Checker"
"Remove Comments"
"Flip Equivalent Binary Trees"
"Moving Average from Data Stream"
"Compare Version Numbers"
"Sum of Subarray Minimums"
"Max Points on a Line"
"Bulls and Cows"
"Subarrays with K Different Integers"
"Stone Game II"
"Number of Atoms"
"Accounts Merge"
"Largest Time for Given Digits"
"Maximum Score Words Formed by Letters"
"Merge Intervals"
"Find Median from Data Stream"
"Integer Replacement"
"Race Car"
"Serialize and Deserialize N-ary Tree"
"Longest Arithmetic Subsequence"
"Divide Array in Sets of K Consecutive Numbers"
"Binary Tree Longest Consecutive Sequence"
"Queue Reconstruction by Height"
"Parallel Courses"
"Path with Maximum Gold"
"Backspace String Compare"
"Path With Minimum Effort"
"Furthest Building You Can Reach"
"Shortest Path Visiting All Nodes"
"Minimum Cost to Make at Least One Valid Path in a Grid"
"Campus Bikes II"
"Matrix Block Sum"
"Rearrange Spaces Between Words"
"Maximum of Absolute Value Expression"
"Surrounded Regions"
"My Calendar III"
"Binary Tree Maximum Path Sum"
"Shopping Offers"
"Design Add and Search Words Data Structure"
"Design A Leaderboard"
"Longest String Chain"
"Design Search Autocomplete System"
"Checking Existence of Edge Length Limited Paths"
"Cat and Mouse"


*/